### ISSUE TITLE
Collect data of different sensors / pins in parallel

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-hardware#110]
Would it be possible to collect data in parallel. E.g. the idea would be that the Android app configures several instruments and transfers the commands to the device to collect data from several pins.

**Comment by bessman** [comment]
This is possible as long as the pins do not use the same underlying hardware or firmware resource.

For example:

- the oscilloscope and logic analyzer cannot be used simultaneously because both store data in the same buffer (firmware limitation).
- The function generator pins (SI1 & SI2) cannot be used at the same time as PWM pins SQ3 and SQ4, because they are controlled by the same MCU pins (C8 & C9) (hardware limitation).

There are improvements that can be made in this area, but those improvements would go in either the firmware or the UI. Closing this as too broad and not hardware related.
